### ISSUE TITLE
想知道你是如何获取论文中dtu的gt的深度图像的

### ISSUE THREAD

**Issue by qwerwsc1** [doubleZ0108/GeoMVSNet#1]

**Comment by doubleZ0108** [comment]
您好，dtu的gt在数据集中有，可以参考[这个代码](https://github.com/doubleZ0108/MVS/blob/master/utils/read_and_visualize_pfm.py)进行可视化

**Comment by qwerwsc1** [comment]
![image](https://github.com/doubleZ0108/GeoMVSNet/assets/101634608/f7716eec-b313-4245-8794-db7a4e9e3678)
无法获得如你论文中层次分明的ground true map

**Comment by doubleZ0108** [comment]
调整可视化时的`v_min`和`v_max`，现在你的可视化是由于深度整体范围太大但实际像素并不具有深度极值造成的层次不明显

**Comment by qwerwsc1** [comment]
问题解决了，十分感谢你的回复和解答。
