### ISSUE TITLE
module 'open3d' has no attribute 'geometry'

### ISSUE THREAD

**Issue by kk6398** [doubleZ0108/GeoMVSNet#11]
您好，我在进行采用open3d对dtu融合时，输入 ”bash scripts/dtu/fusion_dtu.sh“，出现了module 'open3d' has no attribute 'geometry'错误，对应File "fusions/dtu/open3d.py", line 181, in write_ply     pcd = o3d.geometry.PointCloud()。我尝试安装了不同的open3d版本（包括0.17.0、0.15.2、0.13.0），还是出现了相同的错误，请问该怎么debug呢？希望得到您的帮助

**Comment by doubleZ0108** [comment]
请参考此issue https://github.com/doubleZ0108/GeoMVSNet/issues/5

**Comment by kk6398** [comment]
> 请参考此issue #5

感谢回复！
