### ISSUE TITLE
How to use colmap result as input?

### ISSUE THREAD

**Issue by Adolfhill** [doubleZ0108/GeoMVSNet#15]
Thanks to your impressive work!
I am trying to build an object from the Aachen dataset.
I have obtained a result from COLMAP, a widely-used SFM tool, consisting of cameras.bin, database.db, images.bin, and points3D.bin.
I want to use this result to run GeoMVSNet. What should I do?
Thanks a lot!

**Comment by doubleZ0108** [comment]
Please refer to https://github.com/doubleZ0108/GeoMVSNet/issues/9.
