### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by rongirl** [doubleZ0108/GeoMVSNet#17]
Dear author, 
Thank you for your excellent work! Can you provide pretrained model on BlendenMVS?

**Comment by doubleZ0108** [comment]
Sorry, as time has passed for a long time, I reread the hard drive during the experiment and found [a model trained on the BlendedMVS dataset for reference only](https://drive.google.com/file/d/147_UbjE87E-HB9sZ5yLDbckynH825nJd/view?usp=sharing). 

It is emphasized that this model is not a release version and is for reference only.

> I conducted a simple test and found that it do not achieve the desired output. This may be due to we changing the variable names and partial structures in the network during code organization.

**Comment by burui11087** [comment]
> Sorry, as time has passed for a long time, I reread the hard drive during the experiment and found [a model trained on the BlendedMVS dataset for reference only](https://drive.google.com/file/d/147_UbjE87E-HB9sZ5yLDbckynH825nJd/view?usp=sharing).
> 
> It is emphasized that this model is not a release version and is for reference only.
> 
> > I conducted a simple test and found that it do not achieve the desired output. This may be due to we changing the variable names and partial structures in the network during code organization.

This model is the same as the model pretrained on DTU

**Comment by doubleZ0108** [comment]
> > Sorry, as time has passed for a long time, I reread the hard drive during the experiment and found [a model trained on the BlendedMVS dataset for reference only](https://drive.google.com/file/d/147_UbjE87E-HB9sZ5yLDbckynH825nJd/view?usp=sharing).
> > It is emphasized that this model is not a release version and is for reference only.
> > > I conducted a simple test and found that it do not achieve the desired output. This may be due to we changing the variable names and partial structures in the network during code organization.
> 
> This model is the same as the model pretrained on DTU

The model file was from the `blended` folder on my server. So maybe the file is cluttered this way.
