### ISSUE TITLE
DTU Pretrained model

### ISSUE THREAD

**Issue by 13253318778** [doubleZ0108/GeoMVSNet#18]
Hello! Thank you very much for your excellent work. I used the following command to run the DTU pre-trained model you provided: bash scripts/dtu/test_dtu.sh outputs/dtu/test/ depth_est confidence. However, after running this command, I encountered a parameter error. Could you please help me take a look at my issue?
![1706156112277](https://github.com/doubleZ0108/GeoMVSNet/assets/82853287/c1ba26c4-3126-44e7-a334-b6a7daf23dfc)

**Comment by doubleZ0108** [comment]
I think you need to specify the parameters for the custom path. Please refer to the README, we list the example there.

**Comment by 13253318778** [comment]
> I think you need to specify the parameters for the custom path. Please refer to the README, we list the example there.
Thank you very much for your assistance! I have learned how to operate. Wishing you a smooth research journey and a Happy New Year sincerely!
