### ISSUE TITLE
Train issues

### ISSUE THREAD

**Issue by 13253318778** [doubleZ0108/GeoMVSNet#19]
Hello, thank you for your outstanding work. I apologize for disturbing you. After running the training code, I only obtained the following results. Is this normal? I noticed that the epoch is 0/16, and my training stopped at 15/16 by itself. I obtained this output. Could you please confirm if it didn't complete the full run?
![aa14f11f3aacb87ba2ec4f714c49ca1](https://github.com/doubleZ0108/GeoMVSNet/assets/82853287/29b18c3e-2476-4f9b-afe3-4d8757501fdd)
![adf51d8eace3f977620f712862e4218](https://github.com/doubleZ0108/GeoMVSNet/assets/82853287/6109b7fd-b521-4c4a-8542-b4cd01c59af6)

**Comment by doubleZ0108** [comment]
Yes, you made a full training process. We start from 0 and end with 15, which cover 16 epochs totally.

**Comment by 13253318778** [comment]
> Yes, you made a full training process. We start from 0 and end with 15, which cover 16 epochs totally.

Sincerely appreciate your reply. With the upcoming Chinese New Year, I wish you and your family happiness and a joyful New Year!
