### ISSUE TITLE
about the classification loss

### ISSUE THREAD

**Issue by CanCanZeng** [doubleZ0108/GeoMVSNet#21]
Hi, thank you for sharing this great work!
I find that there may be a better method calculating the loss of classification, refer to here  https://github.com/Wuuu3511/LAMVSNET/blob/5eb1461a0d444b6d8205879b7ee16aae504706b8/loss.py#L31. Due to the use of a pyramid structure, if a classification error occurs in the previous stage, the depth candidate of the current layer may not contain the true value. Therefore, it is not reliable to directly assume that the place with the smallest difference is the correct classification result.
https://github.com/doubleZ0108/GeoMVSNet/blob/09167fc95f0400f826625ec700b58288a964ae95/models/loss.py#L59
However, it is also possible that it may not have an impact on the results. I am just sharing my findings.

**Comment by doubleZ0108** [comment]
Thanks for your reminder, I think this is an effective strategy, and I will conduct relevant verification experiments in the future.
