### ISSUE TITLE
How to visualize geometric features in your paper

### ISSUE THREAD

**Issue by duanqg** [doubleZ0108/GeoMVSNet#22]
![977e54753f8f27831b3ec0e41f8f21b](https://github.com/doubleZ0108/GeoMVSNet/assets/70955391/0fd95c3f-e15e-432f-9634-e38dcb1803dc)
Good job!, I noted that there is a geometric feature in your paper, How can I replicate the test and visualize
 it？

**Comment by doubleZ0108** [comment]
You can get a quick visualization here inside the `GeoFeatureFusion` Network

https://github.com/doubleZ0108/GeoMVSNet/blob/09167fc95f0400f826625ec700b58288a964ae95/models/geometry.py#L17-L19

You can visualize the channel layer of features directly, or use some tools as mentioned in  [link1](https://zhuanlan.zhihu.com/p/385858027) or [link2](https://github.com/lartpang/Machine-Deep-Learning/blob/master/%E7%89%B9%E5%BE%81%E5%8F%AF%E8%A7%86%E5%8C%96.md).

**Comment by BenyunZhao** [comment]
Hi, I am now trying to realize and understand the Geometry feature information, and I found that, when I print the shape of features_stage[0] = GeoFeatureFusionNet(...), the shape is [1, 32, 4x downsample W, H], [1, 16, 2x downsample W, H] and [1, 8, original W, H] , the channel=8 is for what?
![Screenshot from 2024-03-26 15-53-42](https://github.com/doubleZ0108/GeoMVSNet/assets/73514526/6e13e873-f171-446d-a357-642d9dc21327)
![Screenshot from 2024-03-26 15-53-58](https://github.com/doubleZ0108/GeoMVSNet/assets/73514526/d317e125-32bc-465c-a297-54b096452fa2)

**Comment by doubleZ0108** [comment]
@ZHAOBenyun I don't fully understand what you mean, can you show the complete code and where you print the tensor?

**Comment by ZHAOBenyun** [comment]
Thank you for your fast! reply! I have attached the total code about printing
![Uploading Screenshot from 2024-03-26 16-02-26.png…]()

**Comment by BenyunZhao** [comment]
Thank you for your fast! reply! I have attached the total code about printing

![Screenshot from 2024-03-26 16-02-26](https://github.com/doubleZ0108/GeoMVSNet/assets/73514526/8aa31675-6af3-47c1-ac69-487bab508ab4)

**Comment by doubleZ0108** [comment]
The geometry fusion network is only designed for reference view (only reference view has the coarse depth estimation from the last stage). Hence, 
- the output of `GeoFeatureFusionNet()` is assign to `[0]` only
- you have 3 output info of L107

The output of L107 is:
```
[B, 32, H/4, W/4]
[B, 16, H/2, W/2]
[B, 8, H, W]
```
The different number of 32, 16, 8 here is the feature channel in different pyramid stages. And Num. 8 is the feature channel of the origin resolution images. This is due to the balance between the information provided by high-resolution images and the GPU consumption.

**Comment by duanqg** [comment]
Thank you for your reply!
And thank you @ZHAOBenyun 
Can I understand that Num 8 in [B, 8, H, W],has 8 channels.
Each Channel represents geometric information.

**Comment by doubleZ0108** [comment]
@duanqg Yes, you understand it absolutely right. However, it should be noted that the geometric features have fused with the original features in L107. Please refer to III.4. and Tab. 4 in our supplement material to explore more.

**Comment by duanqg** [comment]
thank you!
I want to test on my large-scale outdoor custom data
We used the pretrain of DTU, but the result was not good.
Can you open the checkpoint of tnt?

**Comment by doubleZ0108** [comment]
Sorry for that `.ckpt` on TNT dataset was damaged when I organized the project earlier. You can fine-tune the model on the BlendedMVS dataset if you want to test on large-scale outdoor custom data.

**Comment by duanqg** [comment]
Thank you for your patient reply. I will try to train myself
