### ISSUE TITLE
Question about testing at TNT datasets

### ISSUE THREAD

**Issue by llogicall** [doubleZ0108/GeoMVSNet#24]
I am sorry to bother you. I use the checkpoint to get the depth_est, and the visualization is relatively good(I am not sure) ,but the fusion result  is very blurry, only the rough outline and the base can be seen. Is this a parameter selection error during the fusion process, or is the depth_est is not good.
![image](https://github.com/doubleZ0108/GeoMVSNet/assets/42196807/ec5756dc-4d41-46df-ae0a-13366a53abde)

![image](https://github.com/doubleZ0108/GeoMVSNet/assets/42196807/18f6ea82-3e21-4973-b09f-7a9bc84b9ae9)

**Comment by llogicall** [comment]
I have notived that TNT has 3 versions of cams. May I ask if this is the reason？

**Comment by doubleZ0108** [comment]
First, I think you should tune different parameters when fusing depths into point clouds. And in `Meshlab` you use, you can modify the size of points to get a clearer view.

As for 3 versions of cams, I have set the following hyper-parameters. But from my view, I do not see significant differences. Just following one simple principle, use the same cams when estimating depths and fusing point clouds.
