### ISSUE TITLE
About the Memory and Time Consumption

### ISSUE THREAD

**Issue by xingchen2022** [doubleZ0108/GeoMVSNet#3]
Thanks for open-sourcing your excellent work!
I want to inquire about the **Memory and Time Consumption** during the training stage on your device for reference (using the original parameters you have provided)

In my setup, I'm utilizing 2 x RTX8000 GPUs with a batch size of 1. Here are the details:

- Approximately 30GB of memory is being utilized (61G in total) 
- It appears that each epoch requires approximately 15 hours to complete, which means about 10 days to complete the entire training procedure, indicating a rather extended training time？

I appreciate your assistance in providing this information in advance!

**Comment by doubleZ0108** [comment]
Hi Xingchen,
In my settings, we use 4 x Tesla V100 GPUs, and it takes ~40min / epoch and ~10h for coverage (16  epoches).
I never use RTX8000 and don't know the differences in computational power.
The first thing that makes me wonder is whether you train the model in `raw` mode. Because it will consume a lot of memory and time, so please check it.

**Comment by xingchen2022** [comment]
> Hi Xingchen,
> In my settings, we use 4 x Tesla V100 GPUs, and it takes ~40min / epoch and ~10h for coverage (16  epoches).
> I never use RTX8000 and don't know the differences in computational power.
> The first thing that makes me wonder is whether you train the model in `raw` mode. Because it will consume a lot of memory and time, so please check it.

 Thanks for your quick reply！
 Yes I use the raw mode. So you mean you did not use the raw mode?  I wonder if the performance on them Is different? : )

**Comment by doubleZ0108** [comment]
I have tried `raw` mode, it will take ~3 days in our case, so I didn't try a lot.
I have seen other papers claiming that the `raw` mode can improve performance, but I did not observe this in our experiments (maybe we didn't tune parameters).
I think a good method should be able to get a boost from simple input.
Maybe thinking about how to reduce resource consumption for large-resolution reconstruction is a good future concern.

**Comment by xingchen2022** [comment]
Couldn't agree with you more.
I tried normal mode and it will take about 2 hours per epoch, which seems reasonable considering that the RTX8000 has a similar computational capability to the RTX 2080TI.
Thank you very much and hope you have sweet dreams tonight!

**Comment by doubleZ0108** [comment]
Good night.

**Comment by qlihua** [comment]
Hello, I hope this message finds you well. I have tried running the process in normal mode, and it takes  5 hours per epoch on  4090. However, you mentioned that it only takes around two hours on the 2080 Ti. Could you kindly let me know how many GPUs you used, as well as the batch size and memory configuration?
Thank you for your time and assistance!



> Couldn't agree with you more. I tried normal mode and it will take about 2 hours per epoch, which seems reasonable considering that the RTX8000 has a similar computational capability to the RTX 2080TI. Thank you very much and hope you have sweet dreams tonight!

**Comment by xingchen2022** [comment]
> Hello, I hope this message finds you well. I have tried running the process in normal mode, and it takes 5 hours per epoch on 4090. However, you mentioned that it only takes around two hours on the 2080 Ti. Could you kindly let me know how many GPUs you used, as well as the batch size and memory configuration? Thank you for your time and assistance!
> 
> > Couldn't agree with you more. I tried normal mode and it will take about 2 hours per epoch, which seems reasonable considering that the RTX8000 has a similar computational capability to the RTX 2080TI. Thank you very much and hope you have sweet dreams tonight!

sorry, I don't remember details. All I remember is RTX8000 x 2 (96GB in total), and use as large batch as it can afford.

**Comment by qlihua** [comment]
> > Hello, I hope this message finds you well. I have tried running the process in normal mode, and it takes 5 hours per epoch on 4090. However, you mentioned that it only takes around two hours on the 2080 Ti. Could you kindly let me know how many GPUs you used, as well as the batch size and memory configuration? Thank you for your time and assistance!
> > > Couldn't agree with you more. I tried normal mode and it will take about 2 hours per epoch, which seems reasonable considering that the RTX8000 has a similar computational capability to the RTX 2080TI. Thank you very much and hope you have sweet dreams tonight!
> 
> sorry, I don't remember details. All I remember is RTX8000 x 2 (96GB in total), and use as large batch as it can afford.

Thank you for your reply and suggestion. I will try again with a larger batch size.
