### ISSUE TITLE
关于DL方向的MVS与传统MVS的疑问

### ISSUE THREAD

**Issue by changfali** [doubleZ0108/GeoMVSNet#4]
你好，我是最近关注到DL+MVS的，看到这一系列的工作效果好像挺不错的，但是还没来及深入了解。想请教一下，DL方向的MVS与传统的MVS，比如colmap这种，主要的区别是什么呢？可以从精度上、图像及点云分辨率上、图像张数上、显存内存资源开销上简单说一下吗，谢谢。
DL方向的MVS与传统的MVS各有什么缺点呢？还有一个问题就是DL相关的MVS与NeRF精度上区别您是否清楚呢？

**Comment by doubleZ0108** [comment]
It is discussed in https://github.com/doubleZ0108/MVS/issues/2.
