### ISSUE TITLE
Error about open3d_fusion

### ISSUE THREAD

**Issue by maybeLx** [doubleZ0108/GeoMVSNet#5]
I find an error when fuse point cloud, this is because your open3d.py conflicts with the  open3d module when you apply o3d.geometry, it first will find the geometry in open3d.py rather than open3d module. So the straightforward solution is to rename the open3d.py, and "python open3d.py" in  fuse_dtu.sh

**Comment by doubleZ0108** [comment]
It is not an error, it is the problem of different versions of the open3d library.
And thanks for your solution, I will mention this issue in README later.

**Comment by maybeLx** [comment]
Ok, the version of open3d is 0.13.0, and we rename the open3d.py, it works
