### ISSUE TITLE
About the pre-processing of intrinsic parameters

### ISSUE THREAD

**Issue by xingchen2022** [doubleZ0108/GeoMVSNet#6]
Hello,

I hope you're enjoying your time during the national holiday! 
I have a question regarding the intrinsic parameters, specifically related to the following code snippet:

[dataset/dtu.py L245-270](https://github.com/doubleZ0108/GeoMVSNet/blob/807f8eff9eee433ecdd44d8eea6b98ebd41d86a4/datasets/dtu.py#L245-L270)

In my understanding, the camera parameters in the "Camera/train/xxxxxxxx_cam.txt" files are suitable for images with a resolution of 640x512 pixels. Since there are four levels of depth maps with resolutions of (640, 512), (320, 256), (160, 128), and (80, 64), the intrinsic parameters should be scaled down by a factor of 0.5 for each level (1x, 0.5x, 0.25x, 0.125x). However, in the code, it appears that you are using scaling factors of 0.5x, 1x, 2x, and 4x instead. Could you please provide some clarification on this matter? 

Thank you in advance!

**Comment by doubleZ0108** [comment]
I also send you the last blessing of the National Day.

In fact, the DTU dataset we often use is organized by Yao Yao's team in [MVSNet](https://github.com/YoYo000/MVSNet). And in their network architecture, the image (feature) resolution is downscale to 1/4 due to GPU memory limitation. So you can assume that on the same dataset I use, the default camera parameters are aligned with the (160, 128) resolution.

On the contrary, you can see that camera parameters of the T&T dataset are normally processed in the way you said (1x, 0.5x, 0.25x, 0.125x).

In addition, I recommend [my MVSNet analysis blog](https://zhuanlan.zhihu.com/p/460190156) (in Chinese) to you, where you can have a full understanding of the data flow.

**Comment by xingchen2022** [comment]
> I also send you the last blessing of the National Day.
> 
> In fact, the DTU dataset we often use is organized by Yao Yao's team in [MVSNet](https://github.com/YoYo000/MVSNet). And in their network architecture, the image (feature) resolution is downscale to 1/4 due to GPU memory limitation. So you can assume that on the same dataset I use, the default camera parameters are aligned with the (160, 128) resolution.
> 
> On the contrary, you can see that camera parameters of the T&T dataset are normally processed in the way you said (1x, 0.5x, 0.25x, 0.125x).
> 
> In addition, I recommend [my MVSNet analysis blog](https://zhuanlan.zhihu.com/p/460190156) (in Chinese) to you, where you can have a full understanding of the data flow.

Certainly, here's a polished version in English:

Thank you so much for your clear explanation.

I mistakenly associated the resolution of the original image with camera intrinsic parameters, when in fact it should have been related to the depth map's resolution (as you mentioned, (160, 128)). Please forgive my carelessness in not noticing this, even though I have tried some other methods in the MVSNet series...

Your analysis blog is incredibly detailed and immensely helpful for newcomers in the MVS field, and I regret not having seen it earlier, as it would have saved me from many fruitless attempts 🤕

I will definitely recommend it to others. Once again, thank you so much!

**Comment by xingchen2022** [comment]
> I also send you the last blessing of the National Day.
> 
> In fact, the DTU dataset we often use is organized by Yao Yao's team in [MVSNet](https://github.com/YoYo000/MVSNet). And in their network architecture, the image (feature) resolution is downscale to 1/4 due to GPU memory limitation. So you can assume that on the same dataset I use, the default camera parameters are aligned with the (160, 128) resolution.
> 
> On the contrary, you can see that camera parameters of the T&T dataset are normally processed in the way you said (1x, 0.5x, 0.25x, 0.125x).
> 
> In addition, I recommend [my MVSNet analysis blog](https://zhuanlan.zhihu.com/p/460190156) (in Chinese) to you, where you can have a full understanding of the data flow.

Thank you so much for your clear explanation.

I mistakenly associated the resolution of the original image with camera intrinsic parameters, when in fact it should have been related to the depth map's resolution (as you mentioned, (160, 128)). Please forgive my carelessness in not noticing this, even though I have tried some other methods in the MVSNet series...

Your analysis blog is incredibly detailed and immensely helpful for newcomers in the MVS field, and I regret not having seen it earlier, as it would have saved me from many fruitless attempts 🤕

I will definitely recommend it to others. Once again, thank you so much!
