### ISSUE TITLE
关于dtu_evaluation的问题

### ISSUE THREAD

**Issue by Vigoly** [doubleZ0108/GeoMVSNet#7]
非常感谢您精彩的工作！我再按照您的提示运行bash scripts/dtu/matlab_quan_dtu.sh命令时，产生了如下错误：Unable to read file '../../../outputs/dtu/geomvsnet/open3d_quantitative/mvsnet_Eval_1.mat'. No such file or directory.所以想询问一下，由于mvsnet_Eval_1.mat是存在于outputs路径下的，那么它是执行其它命令时生成的吗，还是手动放置到该目录下的呢（在DTU数据集中没找到有该命名的mat文件），再次感谢您的工作，期望收到您的回复。

**Comment by doubleZ0108** [comment]
您好，`.mat`文件是对`.ply`文件进行MATLAB评测得到的数据文件，mat是matlab的缩写，意为matlab特定数据文件格式

如上报错猜想可能原因是您的系统路径下可执行的matlab没有正确配置，可以在对应的根目录下执行`matlab`看看是否有正常输出

**Comment by Vigoly** [comment]
好的好的，谢谢您的回复，我查找一下是哪的问题，祝您科研顺利。
